name: Test
on: push
jobs:
  Job1:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1.2
    - name: Restore packages
      run: nuget restore KaosDiags.sln
    - name: Build test suite
      run: msbuild Test480 /p:Configuration=Debug
    - name: Run test suite
      run: VSTest.Console.exe Test480\bin\Debug\Test480.dll --ResultsDirectory:TestResults
    - uses: actions/upload-artifact@v1
      with:
        name: KaosDiags-Test
        path: .\TestResults